# 사이트 설정

# 테마 지정
theme: jekyll-theme-chirpy

# 웹사이트 언어 설정 › http://www.lingoes.net/en/translator/langcode.htm
lang: ko

# 시간대 설정 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Seoul

# jekyll-seo-tag 설정 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: 나만의 기술 블로그 # 사이트 제목
tagline: 개발을 기록하는 블로그 # 부제목
description: >-
  기술 문서 작성을 위한 미니멀하고 반응형인 Jekyll 테마입니다.

# 배포 주소 (예: https://username.github.io) — 슬래시 `/`로 끝나지 않도록 주의
url: "https://rlagusals1102.github.io"

github:
  username: rlagusals1102

twitter:
  username: your_twitter_username

social:
  name: 김현민 # 본인 이름
  email: your_email@example.com # 이메일 주소
  links:
    - https://twitter.com/your_twitter_username
    - https://github.com/rlagusals1102
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 검색 엔진 인증용 메타태그
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# ↑ --------------------------
# jekyll-seo-tag 설정 끝

# 웹 분석 도구 설정
analytics:
  google:
    id: G-XXXXXXXXXX # 구글 애널리틱스 ID
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# 페이지 조회수 제공자 설정 (현재 goatcounter만 지원)
pageviews:
  provider:

# 다크/라이트 모드 기본값 설정
# 빈 값으로 둘 경우 시스템 설정을 따름
theme_mode: light

# CDN을 사용하는 경우 해당 주소를 지정 (예: 'https://cdn.example.com')
cdn:

# 사이드바에 표시할 아바타 이미지 (URL 또는 로컬 경로)
avatar:

# SEO og:image 설정용 기본 이미지
social_preview_image:

# 전체 글에 대해 목차(TOC) 표시 여부
toc: true

# 댓글 시스템 설정
comments:
  provider: giscus
  giscus:
    repo: rlagusals1102/rlagusals1102.github.io
    repo_id: your_repo_id
    category: General
    category_id: your_category_id
    mapping: pathname
    input_position: bottom
    reactions_enabled: 1
    lang: ko

# 정적 자산을 자가 호스팅할 경우 설정
assets:
  self_host:
    enabled:
    env:

# PWA(웹앱 설치 지원) 설정
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# 페이지네이션: 한 페이지당 글 수
paginate: 10

# 사이트의 baseurl (GitHub Pages의 경우 보통 repository 이름)
baseurl: "/rlagusals1102"

# 아래는 특별한 경우가 아니라면 수정하지 않는 것을 권장합니다

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
